import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

live_config_reload = true

shell = "/usr/bin/zsh"

[cursor.style]
shape = "Block"
blinking = "Always"

[font]
size = 18.0
builtin_box_drawing = true

[font.normal]
family = "monospace"
style = "Regular"

[font.bold]
family = "monospace"
style = "Regular"

[font.bold_italic]
family = "monospace"
style = "Italic"

[font.italic]
family = "monospace"
style = "Italic"


[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[bell]


[[keyboard.bindings]]
chars = "\f"
key = "R"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "R"
mode = "~Vi|~Search"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[scrolling]
history = 100000
multiplier = 4

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "Full"
startup_mode = "Fullscreen"

[window.dimensions]
columns = 0 
lines = 0

[window.padding]
x = 0
y = 0

